// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsqiijqmhwspkvpqufux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzcWlpanFtaHdzcGt2cHF1ZnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTMwNjMsImV4cCI6MjA3MTE4OTA2M30.0t7jzimjTtBW58Luoa7U5pwx2mpsGibuQN5JHdXsNrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});